export interface MemberProfile {
  memberId?: number;
  heightCm?: number | null;
  weightKg?: number | null;
  fitnessGoal?: string | null;
  targetWeightKg?: number | null;
  bodyFatPercentage?: number | null;
  waistCm?: number | null;
  chestCm?: number | null;
  shoulderCm?: number | null;
  hipCm?: number | null;
  neckCm?: number | null;
  armCm?: number | null;
  thighCm?: number | null;
  activityLevel?: string | null;
  trainingExperience?: string | null;
  favoriteWorkoutType?: string | null;
  preferredTrainingDays?: string | null;
  preferredWorkoutTime?: string | null;
  bloodType?: string | null;
  medicalConditions?: string | null;
  allergies?: string | null;
  injuries?: string | null;
  medications?: string | null;
  doctorClearanceRequired?: boolean;
  healthNotes?: string | null;
  emergencyContactName?: string | null;
  emergencyContactRelationship?: string | null;
  emergencyContactPhone?: string | null;
  emergencyContactAltPhone?: string | null;
  dailyCaloriesTarget?: number | null;
  proteinTargetGrams?: number | null;
  carbsTargetGrams?: number | null;
  fatTargetGrams?: number | null;
  waterTargetMl?: number | null;
  language?: string | null;
  theme?: string | null;
  measurementUnit?: string | null;
  notificationsEnabled?: boolean;
  profilePhotoUrl?: string | null;
  profileCompletionPercentage?: number | null;
}
