ALTER TABLE public.member_profiles
ALTER COLUMN profile_photo_url DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_check_ins_one_open_per_member
ON public.check_ins(member_id)
WHERE check_out_time IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_class_bookings_one_active_per_member_class
ON public.class_bookings(class_id, member_id)
WHERE status IN ('BOOKED', 'Booked');

CREATE TABLE IF NOT EXISTS public.membership_plan_branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_plan_id BIGINT NOT NULL,
  branch_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_membership_plan_branches_plan
    FOREIGN KEY (membership_plan_id)
    REFERENCES public.membership_plans(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_membership_plan_branches_branch
    FOREIGN KEY (branch_id)
    REFERENCES public.branches(id)
    ON DELETE CASCADE,
  CONSTRAINT uq_membership_plan_branches_plan_branch
    UNIQUE (membership_plan_id, branch_id)
);
