CREATE TABLE IF NOT EXISTS public.membership_plan_branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  membership_plan_id BIGINT NOT NULL,
  branch_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_membership_plan_branches_plan
    FOREIGN KEY (membership_plan_id)
    REFERENCES public.membership_plans(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_membership_plan_branches_branch
    FOREIGN KEY (branch_id)
    REFERENCES public.branches(id)
    ON DELETE CASCADE,
  CONSTRAINT uq_membership_plan_branches_plan_branch
    UNIQUE (membership_plan_id, branch_id)
);

ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS capacity INTEGER;

ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS open_time TIME;

ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS close_time TIME;

CREATE INDEX IF NOT EXISTS ix_membership_plan_branches_plan_id
ON public.membership_plan_branches(membership_plan_id);

CREATE INDEX IF NOT EXISTS ix_membership_plan_branches_branch_id
ON public.membership_plan_branches(branch_id);

CREATE INDEX IF NOT EXISTS ix_check_ins_active_branch
ON public.check_ins(branch_id)
WHERE check_out_time IS NULL;
