create table if not exists public.device_approvals (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  device_id text not null,
  is_approved boolean not null default false,
  last_updated_at timestamp with time zone not null default now(),
  created_at timestamp with time zone default now()
);

create index if not exists ix_device_approvals_user_id
  on public.device_approvals (user_id);

create table if not exists public.otp_records (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  device_id text not null,
  otp_code text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  is_used boolean not null default false
);

create index if not exists ix_otp_records_user_device
  on public.otp_records (user_id, device_id);

create table if not exists public.refresh_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  refresh_token text not null unique,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now(),
  revoked_at timestamp with time zone
);

create index if not exists ix_refresh_sessions_user_id
  on public.refresh_sessions (user_id);

create table if not exists public.location_presence (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id),
  latitude numeric not null,
  longitude numeric not null,
  inside_gym boolean not null,
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  duration_seconds integer not null,
  completed_at timestamp with time zone not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists ix_workout_sessions_user_id
  on public.workout_sessions (user_id);

create table if not exists public.member_profiles (
  id bigint generated by default as identity primary key,
  member_id bigint not null unique references public.members(id),
  height_cm numeric,
  weight_kg numeric,
  fitness_goal text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

insert into public.member_profiles (
  member_id,
  height_cm,
  weight_kg,
  fitness_goal,
  created_at,
  updated_at
)
select
  members.id,
  176,
  74,
  'Build strength and improve conditioning',
  now(),
  now()
from public.members
left join public.member_profiles
  on member_profiles.member_id = members.id
where member_profiles.member_id is null;
